### ISSUE TITLE
assembly-1.1.0.jar is not supported in Android 7.0

### ISSUE THREAD

**Issue by SureshKumarSelvaraj** [Code-House/bacnet4j-wrapper#10]
I am Using assembly-1.1.0.jar(BACnet4j-5.0.0) in my android application to create bacnet objects in my android app.

To Reproduce

Add assembly-1.1.0.jar(BACnet4j-5.0.0) as library in android project
RUN in android 7.0 device
Getting Run time error
"java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;"

Android 7.0 is not supporting all the features of JAVA 8.
Supports only the following
  Lambda expressions
  Method references
  Type annotations
  Default and static interface methods
  Repeating annotations

Java.time is not supported by android 7.0.

Suggest me some solution to make assembly-1.1.0.jar(BACnet4j-5.0.0) compatible with android 7.0.

Thanks.

**Comment by splatch** [comment]
Hey @SureshKumarSelvaraj, library wasn't made with any plans to run under android. While I understand the need we can't stick with older versions of Java which are out of support.

You can try to emulate `java.time` packages via "backport" JARs: https://github.com/ThreeTen/threetenbp

Best,
Łukasz
