### ISSUE TITLE
支持BBMD 

### ISSUE THREAD

**Issue by dufu-byte** [Code-House/bacnet4j-wrapper#18]
hello ，Do you support BBMD

**Comment by splatch** [comment]
BBMD is supported directly by underlying library. Wrapper does not do much about handling of broadcast information. On top of that I've added support for manual population of network routing table: https://github.com/Code-House/bacnet4j-wrapper/blob/993a38d5aaca9aaddfcd393abdd038db9e4f98b0/ip/src/main/java/org/code_house/bacnet4j/wrapper/ip/BacNetIpClient.java#L74

**Comment by dufu-byte** [comment]
好的，我尝试下

**Comment by splatch** [comment]
This is something which is relevant from client/device point of view. It does not help with implementation of BACnet Broadcast Management Device functionality.

**Comment by splatch** [comment]
No further work is planed in this area, hence closing issue for now. Please reopen if you find it critical for your use case with this library.
