### ISSUE TITLE
Unsupported BACnet Object "Notification-Class" exception

### ISSUE THREAD

**Issue by saransh14** [Code-House/bacnet4j-wrapper#24]
On using bacnet4j-wrapper APIs for fetching the present values of all the objects associated to a bacnet device, I'm getting an exception `UnsupportedTypeException`.
![image](https://github.com/Code-House/bacnet4j-wrapper/assets/21282950/8460c6c3-485a-4641-b366-6f13413c5ea3)

Please provide the support for Notification-Class, so that I can extract the data out of the device.

Thanks,
Saransh

**Comment by saransh14** [comment]
@splatch Can you please let me know the release version which I shall use to pull in the latest changes that you've done for providing support for Notification Class object type.
I can see the `maven release` workflow action failing for release of the updated code.

**Comment by splatch** [comment]
Latest version (1.3.0-SNAPSHOT) should be available through sonatype-oss: https://oss.sonatype.org/content/repositories/snapshots/

Let me know if it works for you, if so I'll cut a final release of 1.3.0.

**Comment by saransh14** [comment]
Hi @splatch thanks for sharing the snapshot version, although the unsupported exceptions is solved, but still unable to fetch the value using `client.getPresentValue(bacnetObject, new BypassBacnetConverter())` method.

Getting the following exception: 

`2023-11-02T06:52:20.762Z ERROR 1 --- [   scheduling-1] o.w.b.s.service.impl.BacnetServiceImpl   : Property Name : Notification Class 1 :: Error occurred : org.code_house.bacnet4j.wrapper.api.BacNetClientException: Could not get property value`


Same exception is coming for `trendLog` object type:

`2023-11-02T06:52:20.945Z ERROR 1 --- [   scheduling-1] o.w.b.s.service.impl.BacnetServiceImpl   : Property Name : Trend Log 1 :: Error occurred : org.code_house.bacnet4j.wrapper.api.BacNetClientException: Could not get property value`

**Comment by splatch** [comment]
@saransh14 do you have a stack trace which covers library/wrapper. Failure in retrieval might be result of several things, knowing cause will help me with fix.

**Comment by saransh14** [comment]
@splatch unable to generate the stack trace of the library/wrapper. Sharing the exception object with the parameter values

<img width="520" alt="image" src="https://github.com/Code-House/bacnet4j-wrapper/assets/21282950/6f148e9b-c04a-460d-95e3-89c7a80eed61">

**Comment by saransh14** [comment]
@splatch any update on this issue?

**Comment by splatch** [comment]
Not yet, I tested with devices I have, but none of them has notification class property within objects. I have to wire in another device (IOM from Johnson/Metasys) in order to check what going on.

Since this library does not use reflection the `InvocationTargetException` you see might come from upper layers., Can you look deeper if there is maybe actual cause?

**Comment by splatch** [comment]
@saransh14 I've checked with manually coded bacnet/ip server and it seem to work. Below is output from discovery main which list object properties:

```
          => Type ANALOG_INPUT id: 1
             Metadata
               Name: test1
               Units: watt-hours
               Description: 
             Present value 12.060566, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'acked-transitions' value EventTransitionBits [to-offnormal=true, to-fault=true, to-normal=true], type: com.serotonin.bacnet4j.type.constructed.EventTransitionBits
             Attribute 'event-time-stamps' value [TimeStamp [choice=DateTime [date=Date [year=255, month=UNSPECIFIED, day=255, dayOfWeek=UNSPECIFIED], time=255:255:255.255]], TimeStamp [choice=DateTime [date=Date [year=255, month=UNSPECIFIED, day=255, dayOfWeek=UNSPECIFIED], time=255:255:255.255]], TimeStamp [choice=DateTime [date=Date [year=123, month=NOVEMBER, day=6, dayOfWeek=MONDAY], time=10:4:31.57]]], type: com.serotonin.bacnet4j.type.constructed.SequenceOf
             Attribute 'interface-value' value OptionalReal [choice=Null], type: com.serotonin.bacnet4j.type.constructed.OptionalReal
             Attribute 'fault-high-limit' value 120.0, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'fault-low-limit' value 0.0, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'notify-type' value alarm, type: com.serotonin.bacnet4j.type.enumerated.NotifyType
             Attribute 'out-of-service' value false, type: com.serotonin.bacnet4j.type.primitive.Boolean
             Attribute 'notification-class' value 17, type: com.serotonin.bacnet4j.type.primitive.UnsignedInteger
             Attribute 'present-value' value 11.430752, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'deadband' value 5.0, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'event-message-texts' value [, , ], type: com.serotonin.bacnet4j.type.constructed.SequenceOf
             Attribute 'event-message-texts-config' value [, , ], type: com.serotonin.bacnet4j.type.constructed.SequenceOf
             Attribute 'event-detection-enable' value true, type: com.serotonin.bacnet4j.type.primitive.Boolean
             Attribute 'event-algorithm-inhibit' value false, type: com.serotonin.bacnet4j.type.primitive.Boolean
             Attribute 'event-enable' value EventTransitionBits [to-offnormal=true, to-fault=true, to-normal=true], type: com.serotonin.bacnet4j.type.constructed.EventTransitionBits
             Attribute 'event-state' value normal, type: com.serotonin.bacnet4j.type.enumerated.EventState
             Attribute 'time-delay-normal' value 2, type: com.serotonin.bacnet4j.type.primitive.UnsignedInteger
             Attribute 'reliability-evaluation-inhibit' value false, type: com.serotonin.bacnet4j.type.primitive.Boolean
             Attribute 'reliability' value no-fault-detected, type: com.serotonin.bacnet4j.type.enumerated.Reliability
             Attribute 'high-limit' value 100.0, type: com.serotonin.bacnet4j.type.primitive.Real
             Attribute 'status-flags' value StatusFlags [in-alarm=false, fault=false, overridden=false, out-of-service=false], type: com.serotonin.bacnet4j.type.constructed.StatusFlags
             Attribute 'time-delay' value 1, type: com.serotonin.bacnet4j.type.primitive.UnsignedInteger
             Attribute 'limit-enable' value LimitEnable [low-limit-enable=true, high-limit-enable=true], type: com.serotonin.bacnet4j.type.constructed.LimitEnable
             Attribute 'units' value watt-hours, type: com.serotonin.bacnet4j.type.enumerated.EngineeringUnits
             Attribute 'low-limit' value 20.0, type: com.serotonin.bacnet4j.type.primitive.Real
```

**Comment by saransh14** [comment]
Hi @splatch, can you please cut a release and share the new version for the artificat, so that I can use the same.
Thanks in advance.

**Comment by saransh14** [comment]
Hi @splatch, can you please share the final release version for 1.3.x, which I can use to fetch out the NotificationClass object types.

**Comment by splatch** [comment]
I wish to, I attempted to make an release yesterday but it failed. Have to tinker build in order to get it working.

**Comment by saransh14** [comment]
Ok Sure, please let me know once the release is available, I'll use the same to extract the data for NotificationClass object types.

**Comment by saransh14** [comment]
Hey @splatch , any update on the final release build?

**Comment by splatch** [comment]
Sorry, I am stuck with some opcua work. If you need a binary please stick with https://oss.sonatype.org/content/groups/public/ for now. Latest snapshot with necessary fixes is there.
I'll be working on release close to Christmas.
