### ISSUE TITLE
client.setPropertyValue - priority level

### ISSUE THREAD

**Issue by plucpel** [Code-House/bacnet4j-wrapper#7]
I am using the openhab binding and trying to set value for some AnalogOutput items. I can set the values using another tool if I use a priority of 8 or above. Seems like the wrapper is using a lower priority so my values are not getting accepted on some items.

Is there a way to set this in the config ?

**Comment by plucpel** [comment]
@splatch any ideas on this ? Does the option exist within your wrapper or would it be an enhancement ?

I use it (through the openhab binding) and certain items on my bacnet network cannot be controlled without setting a certain priority with the setPropertyValue...

Thanks !

**Comment by splatch** [comment]
Hey @plucpel, I missed intial nitification, and yes wrapper does not specify priority level. This is defonitely an enhancement we can add.

**Comment by plucpel** [comment]
Thanks @splatch. Let me know if I can help with testing once you are ready.
